name: conda-fadip
channels:
  - conda-forge
dependencies:
  - fastapi=0.70.1
  - uvicorn=0.16.0
  - pip=21.3.1
  - pyod=0.9.7
  - dask
  - xgboost=1.5.0
  - pytorch
  - torchvision
  - psycopg2=2.8.6
  - pip:
      - pystan==2.19.1.1
      - prometheus-api-client==0.4.2
      - prometheus-client==0.12.0
      - prometheus-pandas==0.3.0
      - jsonschema==4.3.3
      - PyYAML==6.0
      - boto3==1.20.28
      - prophet==1.0.1
      - SQLAlchemy==1.4.29
      - slack-sdk==3.13.0
      - pymsteams==0.1.16



